version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8000 && npm run dev
    container_name: laravel_app
    ports:
      - "8000:8000"
      - "5173:5173"  
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: laravel_mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: